apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bl45p
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: bl45p
  destination:
    name: argus
    namespace: bl45p
  source:
    path: apps
    repoURL: https://github.com/epics-containers/bl45p-apps.git
    targetRevision: main
    helm:
      version: v3
      valueFiles:
        - https://raw.githubusercontent.com/epics-containers/bl45p/main/services/beamline_values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
