# This file configures an ArgoCD app of apps that represent a beamline or
# group of accelerator IOCs and services. The details of the services are
# configured in the separate repo indicated by repoURL.

# This repostory only controls which services and which versions of those
# services should be running on the cluster. It is recommended that this repo
# be updated by a CI/CD pipeline or configuration tools only.

project: bl45p

appDestination:
  name: argus
  namespace: bl45p

serviceDestination:
  name: pollux
  namespace: bl45p

source:
  repoURL: https://github.com/epics-containers/bl45p.git
  targetRevision: add-extra-app-layer

# list of services to deploy. Each item is of the form:
# - service: service name as it appears in K8S (statefulset/deployment name)
#   targetRevision: optional override for targetRevision above
#   repoURL: optional override for git repo to source the helm chart from
#            the path is always services/<service> within that repo
#   enabled: set to false to turn off an IOC
#   removed: set to true to remove the app from cluster

services:
  # shared epics services ######################################################
  epics-pvcs:
  epics-opis:

  # daq services ###############################################################
  daq-rabbitmq:
    # this service always restarts if you don't pin it (must have a random seed)
    targetRevision: 2024.7.5
  daq-blueapi:
  daq-nexus:

  # epics iocs #################################################################

  bl45p-ea-dcam-01:
    enabled: false
  bl45p-ea-dcam-02:
  bl45p-mo-panda-01:
  bl45p-mo-panda-02:
  bl45p-mo-brick-01:
